[package]
name = "ham_dos"
version = "0.1.0"
authors = ["shakram02 <ahmedhamdyau@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"